from yacs.config import CfgNode as CN
_CN = CN()


def lower_config(yacs_cfg):
    if not isinstance(yacs_cfg, CN):
        return yacs_cfg
    return {k.lower(): lower_config(v) for k, v in yacs_cfg.items()}

##############  ↓  ThreeDSAM   ↓  ##############
_CN = CN()
_CN.N_ITER = 2
_CN.LAYER_ASSIGN = [0, 1]
_CN.BACKBONE_TYPE = 'ResNetFPN'
_CN.RESOLUTION = (8, 2)  # options: [(8, 2), (16, 4)]
_CN.D_STRUCT = 128
_CN.FINE_WINDOW_SIZE = 5  # window_size in fine_level, must be odd
_CN.FINE_CONCAT_COARSE_FEAT = True

# 1. 3DSAM-backbone & feature fusion config
_CN.RESNETFPN = CN()
_CN.RESNETFPN.INITIAL_DIM = 128
_CN.RESNETFPN.BLOCK_DIMS = [128, 196, 256]

# 2. 3DSAM initialization coarse level attention config
_CN.COARSE_INIT = CN()
_CN.COARSE_INIT.MP = False
_CN.COARSE_INIT.HALF = False
_CN.COARSE_INIT.D_MODEL = 256
_CN.COARSE_INIT.D_FFN = 256
_CN.COARSE_INIT.NHEAD = 8
_CN.COARSE_INIT.LAYER_NAMES = ['self', 'cross'] * 4
_CN.COARSE_INIT.AGG_SIZE0 = 1
_CN.COARSE_INIT.AGG_SIZE1 = 1
_CN.COARSE_INIT.NO_FLASH = True
_CN.COARSE_INIT.ROPE = True  
_CN.COARSE_INIT.NPE = [480, 640, 480, 640]
_CN.COARSE_INIT.LINEAR_ATTENTION = True

# 3.1. 3DSAM 3D structure feature extractor config
_CN.EXTRACTOR = CN()
_CN.EXTRACTOR.ANCHOR_NUM = 32  # for training
_CN.EXTRACTOR.ANCHOR_NUM_MIN = 8  # for test/val
_CN.EXTRACTOR.ANCHOR_THR = 0.3
_CN.EXTRACTOR.BORDER_RM = 2
_CN.EXTRACTOR.D_COLOR = 256
_CN.EXTRACTOR.D_STRUCT = 128 # D_STRUCT = ANCHOR_NUM * 4

# 3.2 self-attention module config
_CN.SELF_ATTENTION = CN()
_CN.SELF_ATTENTION.MP = False
_CN.SELF_ATTENTION.HALF = False
_CN.SELF_ATTENTION.D_MODEL = 256
_CN.SELF_ATTENTION.NHEAD = 8
_CN.SELF_ATTENTION.LAYER_NAMES = ['self'] * 1
_CN.SELF_ATTENTION.AGG_SIZE0 = 1
_CN.SELF_ATTENTION.AGG_SIZE1 = 1
_CN.SELF_ATTENTION.NO_FLASH = True
_CN.SELF_ATTENTION.ROPE = True  
_CN.SELF_ATTENTION.NPE = [480, 640, 480, 640]
_CN.SELF_ATTENTION.LINEAR_ATTENTION = True

# 3.3 fetch-struct-info cross attention module config
_CN.FETCH_STRUCT_CROSS_ATTENTION = CN()
_CN.FETCH_STRUCT_CROSS_ATTENTION.MP = False
_CN.FETCH_STRUCT_CROSS_ATTENTION.HALF = False
_CN.FETCH_STRUCT_CROSS_ATTENTION.D_MODEL = 256
_CN.FETCH_STRUCT_CROSS_ATTENTION.NHEAD = 8
_CN.FETCH_STRUCT_CROSS_ATTENTION.LAYER_NAMES = ['cross'] * 1
_CN.FETCH_STRUCT_CROSS_ATTENTION.AGG_SIZE0 = 1
_CN.FETCH_STRUCT_CROSS_ATTENTION.AGG_SIZE1 = 1
_CN.FETCH_STRUCT_CROSS_ATTENTION.NO_FLASH = True
_CN.FETCH_STRUCT_CROSS_ATTENTION.ROPE = True  
_CN.FETCH_STRUCT_CROSS_ATTENTION.NPE = [480, 640, 480, 640]
_CN.FETCH_STRUCT_CROSS_ATTENTION.LINEAR_ATTENTION = True

# 3.4 geometric-attention module config
_CN.GEOMETRIC_ATTENTION = CN()
_CN.GEOMETRIC_ATTENTION.D_MODEL = 256 
_CN.GEOMETRIC_ATTENTION.NHEAD = 8 
_CN.GEOMETRIC_ATTENTION.AREA_WIDTH = 4
_CN.GEOMETRIC_ATTENTION.MP = False
_CN.GEOMETRIC_ATTENTION.HALF = False
_CN.GEOMETRIC_ATTENTION.D_FFN = 256
_CN.GEOMETRIC_ATTENTION.AGG_SIZE0 = 1
_CN.GEOMETRIC_ATTENTION.AGG_SIZE1 = 1
_CN.GEOMETRIC_ATTENTION.NO_FLASH = True
_CN.GEOMETRIC_ATTENTION.ROPE = False  
_CN.GEOMETRIC_ATTENTION.NPE = [480, 640, 480, 640]
_CN.GEOMETRIC_ATTENTION.LINEAR_ATTENTION = True

# 4. Coarse-Matching config
_CN.MATCH_COARSE = CN()
_CN.MATCH_COARSE.MATCH_TYPE = 'dual_softmax' 
_CN.MATCH_COARSE.THR = 0.2
_CN.MATCH_COARSE.BORDER_RM = 2
_CN.MATCH_COARSE.DSMAX_TEMPERATURE = 0.1
_CN.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.2  # training tricks: save GPU memory
_CN.MATCH_COARSE.TRAIN_PAD_NUM_GT_MIN = 200  # training tricks: avoid DDP deadlock
_CN.MATCH_COARSE.SPARSE_SPVS = True

# 5. fine module config
_CN.FINE = CN()
_CN.FINE.MP = False
_CN.FINE.HALF = False
_CN.FINE.AREA_WIDTH = None
_CN.FINE.D_MODEL = 128
_CN.FINE.NHEAD = 8
_CN.FINE.LAYER_NAMES = ['self', 'cross'] * 1
_CN.FINE.AGG_SIZE0 = 1
_CN.FINE.AGG_SIZE1 = 1
_CN.FINE.NO_FLASH = True
_CN.FINE.ROPE = True  
_CN.FINE.NPE = [480, 640, 480, 640]
_CN.FINE.LINEAR_ATTENTION = True

default_cfg = lower_config(_CN)